# Generated by Django 5.0.3 on 2024-06-09 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_conversation_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='modified_at',
        ),
    ]
