# Generated by Django 5.0.3 on 2024-06-09 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_conversation_modified_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversationmessage',
            name='sent_to',
        ),
    ]
