# Generated by Django 5.0.3 on 2024-04-09 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('news', '0003_news_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='created_for',
            field=models.ManyToManyField(related_name='allowed_news', to='auth.group', verbose_name='Новость для'),
        ),
    ]
