# Generated by Django 5.0.3 on 2024-04-14 13:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_news_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='created_at',
            new_name='created_at_datetime',
        ),
        migrations.RemoveField(
            model_name='news',
            name='created_for',
        ),
        migrations.AddField(
            model_name='news',
            name='created_at_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
    ]
