# Generated by Django 5.0.3 on 2024-04-14 14:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('news', '0007_alter_news_created_at_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='created_at_date',
        ),
        migrations.RemoveField(
            model_name='news',
            name='created_at_datetime',
        ),
        migrations.AddField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата и время создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='created_for',
            field=models.ManyToManyField(related_name='allowed_news', to='auth.group', verbose_name='Новость для'),
        ),
    ]
