# Generated by Django 5.0.3 on 2024-04-21 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('news', '0010_remove_news_created_for_news_created_for_group_and_more'),
        ('study_groups', '0003_remove_school_name_school_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='created_for_group',
            field=models.ManyToManyField(blank=True, related_name='allowed_news', to='auth.group', verbose_name='Новость для группы'),
        ),
        migrations.AlterField(
            model_name='news',
            name='created_for_studygroup',
            field=models.ManyToManyField(blank=True, related_name='allowed_news', to='study_groups.studygroup', verbose_name='Новость для класса'),
        ),
    ]
