# Generated by Django 5.0.3 on 2024-04-21 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_alter_news_created_for_group_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='created_for_group',
            new_name='created_for_groups',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='created_for_studygroup',
            new_name='created_for_studygroups',
        ),
    ]
