# Generated by Django 5.0.3 on 2024-05-13 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_remove_news_long_description_remove_news_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='created_for_studygroups',
            new_name='created_for_study_groups',
        ),
    ]
