# Generated by Django 5.0.3 on 2024-05-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_rename_created_for_studygroups_news_created_for_study_groups'),
        ('study_groups', '0003_remove_school_name_school_full_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='created_for_groups',
        ),
        migrations.AddField(
            model_name='news',
            name='created_for',
            field=models.CharField(blank=True, choices=[('teacher', 'Учитель'), ('student', 'Ученик'), ('tutor', 'Куратор')], max_length=25, null=True, verbose_name='Роль читателей'),
        ),
        migrations.AlterField(
            model_name='news',
            name='created_for_study_groups',
            field=models.ManyToManyField(blank=True, related_name='news', to='study_groups.studygroup', verbose_name='Класс читателей'),
        ),
    ]
