# Generated by Django 5.0.3 on 2024-04-29 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='preview_description',
            field=models.CharField(blank=True, max_length=126, null=True, verbose_name='Описание для превью'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=126, verbose_name='Название'),
        ),
    ]
