# Generated by Django 5.0.3 on 2024-04-29 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_preview_description_alter_course_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='preview_description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание для превью'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
