# Generated by Django 5.0.3 on 2024-05-01 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_preview_description_alter_course_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Контент')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликован')], default='draft', max_length=20, verbose_name='Статус')),
                ('lesson_type', models.CharField(choices=[('article', 'Статья'), ('quiz', 'Викторина'), ('video', 'Видео')], default='article', max_length=20, verbose_name='Тип')),
                ('youtube_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='Ссылка на видео')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, null=True, verbose_name='Вопрос')),
                ('answer', models.CharField(max_length=255, null=True, verbose_name='Правильный ответ')),
                ('opt1', models.CharField(max_length=255, null=True, verbose_name='Неправильный ответ 1')),
                ('opt2', models.CharField(max_length=255, null=True, verbose_name='Неправильный ответ 2')),
                ('opt3', models.CharField(max_length=255, null=True, verbose_name='Неправильный ответ 3')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='courses.lesson', verbose_name='Викторина')),
            ],
            options={
                'verbose_name': 'Викторина',
                'verbose_name_plural': 'Викторины',
            },
        ),
    ]
