# Generated by Django 5.0.3 on 2024-05-01 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_lesson_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='courses.lesson', verbose_name='Урок'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='opt1',
            field=models.CharField(max_length=255, null=True, verbose_name='Ответ 1'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='opt2',
            field=models.CharField(max_length=255, null=True, verbose_name='Ответ 2'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='opt3',
            field=models.CharField(max_length=255, null=True, verbose_name='Ответ 3'),
        ),
    ]
