# Generated by Django 5.0.3 on 2024-05-13 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_lesson_chapter'),
        ('study_groups', '0006_remove_studygroup_teachers_remove_studygroup_tutors'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='created_for',
            field=models.ManyToManyField(related_name='courses', to='study_groups.studygroup', verbose_name='Классы'),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_courses', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
    ]
