# Generated by Django 5.0.3 on 2024-06-06 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_chapter_list_order_lesson_list_order'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together={('course', 'list_order')},
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('chapter', 'list_order')},
        ),
    ]
