# Generated by Django 5.0.3 on 2024-06-09 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_alter_chapter_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='list_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядковый номер в курсе'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='list_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядковый номер в главе'),
        ),
    ]
