# Generated by Django 5.0.3 on 2024-06-09 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_alter_chapter_list_order_alter_lesson_list_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='image',
        ),
    ]
