# Generated by Django 5.0.3 on 2024-06-09 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_chapter_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news', verbose_name='Изображение'),
        ),
    ]
