# Generated by Django 5.0.3 on 2024-06-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_alter_quiz_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='opt4',
            field=models.CharField(max_length=255, null=True, verbose_name='Ответ 4'),
        ),
    ]
