# Generated by Django 5.0.3 on 2024-04-08 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_short_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='short_description',
        ),
    ]
