# Generated by Django 5.0.3 on 2024-04-21 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_groups', '0003_remove_school_name_school_full_name_and_more'),
        ('users', '0006_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='school',
            field=models.ManyToManyField(related_name='members', to='study_groups.studygroup', verbose_name='Школа'),
        ),
    ]
