# Generated by Django 5.0.3 on 2024-04-21 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_groups', '0003_remove_school_name_school_full_name_and_more'),
        ('users', '0007_customuser_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='school',
        ),
        migrations.AddField(
            model_name='customuser',
            name='studygroup',
            field=models.ManyToManyField(related_name='members', to='study_groups.studygroup', verbose_name='Класс'),
        ),
    ]
