# Generated by Django 5.0.3 on 2024-04-21 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_customuser_school_customuser_studygroup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='studygroup',
            new_name='studygroups',
        ),
    ]
