# Generated by Django 5.0.3 on 2024-05-13 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_customuser_studygroups'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='studygroups',
            new_name='study_groups',
        ),
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('teacher', 'Учитель'), ('student', 'Ученик'), ('tutor', 'Куратор')], default='Ученик', max_length=25, verbose_name='Роль'),
            preserve_default=False,
        ),
    ]
