# Generated by Django 5.0.3 on 2024-05-13 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_rename_studygroups_customuser_study_groups_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='status',
            new_name='role',
        ),
    ]
