# Generated by Django 5.0.3 on 2024-05-13 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_rename_status_customuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='study_groups',
        ),
    ]
