# Generated by Django 5.0.3 on 2024-05-13 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_groups', '0006_remove_studygroup_teachers_remove_studygroup_tutors'),
        ('users', '0013_remove_customuser_study_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='study_groups',
            field=models.ManyToManyField(blank=True, related_name='members', to='study_groups.studygroup', verbose_name='Класс'),
        ),
    ]
