# Generated by Django 5.0.3 on 2024-05-31 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_customuser_study_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('teacher', 'Учитель'), ('student', 'Ученик'), ('tutor', 'Куратор')], max_length=25, null=True, verbose_name='Роль'),
        ),
    ]
