# Generated by Django 5.0.3 on 2024-05-31 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_outsourced',
            field=models.BooleanField(default=False, verbose_name='Внешний пользователь'),
        ),
    ]
