# Generated by Django 5.0.3 on 2024-04-19 12:14

import study_groups.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='entrance_year',
            field=models.IntegerField(default=2020, validators=[study_groups.validators.validate_year], verbose_name='Год поступления'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studygroup',
            name='graduation_yeaer',
            field=models.IntegerField(default=2022, validators=[study_groups.validators.validate_year], verbose_name='Год выпуска'),
            preserve_default=False,
        ),
    ]
