# Generated by Django 5.0.3 on 2024-04-19 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_groups', '0002_studygroup_entrance_year_studygroup_graduation_yeaer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='name',
        ),
        migrations.AddField(
            model_name='school',
            name='full_name',
            field=models.CharField(default='test', max_length=255, verbose_name='Полное наименование'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='short_name',
            field=models.CharField(default='test', max_length=255, verbose_name='Короткое наименование'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='studygroup',
            unique_together={('grade', 'letter', 'school', 'entrance_year', 'graduation_yeaer')},
        ),
    ]
