# Generated by Django 5.0.3 on 2024-05-31 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_groups', '0006_remove_studygroup_teachers_remove_studygroup_tutors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studygroup',
            old_name='graduation_yeaer',
            new_name='graduation_year',
        ),
        migrations.AlterUniqueTogether(
            name='studygroup',
            unique_together={('grade', 'letter', 'school', 'entrance_year', 'graduation_year')},
        ),
    ]
