# Generated by Django 5.0.3 on 2024-06-09 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_groups', '0007_rename_graduation_yeaer_studygroup_graduation_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studygroup',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='study_groups', to='study_groups.school', verbose_name='Школа'),
            preserve_default=False,
        ),
    ]
